packages:
  - packages/*
  - services/*

catalog:
  '@types/node': 25.0.9
  dayjs: 1.11.19
  tsup: 8.5.1
  typescript: 5.9.3
  zod: 4.3.5

sharedWorkspaceLockfile: false

onlyBuiltDependencies:
  - lefthook
