packages:
  - packages/*
  - services/*

catalog:
  '@types/node': 20.19.25
  dayjs: 1.11.19
  tsup: 8.5.1
  typescript: 5.9.3
  zod: 4.2.1

sharedWorkspaceLockfile: false

onlyBuiltDependencies:
  - lefthook
